### ISSUE TITLE
Add documentation for the HTTP client

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris-client-http#3]
The TypeScript client SDKs are documented [here](https://www.tigrisdata.com/docs/sdkstools/). We need documentation for the HTTP client, which follows the same structure as the [TypeScript](https://www.tigrisdata.com/docs/sdkstools/typescript/) documentation.

**Comment by ovaistariq** [comment]
@akhill10 as you implemented this client library, are you interested in wrapping it up and adding the documentation as well?

**Comment by akhill10** [comment]
@ovaistariq Client library is not completed yet. I will try to wrap it up in next couple of weeks. And yeah, I will do the documentation as well, once it's finished.

**Comment by ovaistariq** [comment]
Sounds good. I'll make sure to assign this to you then.
